name: Debug Polkadot Integration Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  polkadot:
    name: Polkadot Integration test
    runs-on: solang-ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Start substrate contracts node
      - name: Start substrate contracts node
        run: echo id=$(docker run -d -p 9944:9944 ghcr.io/hyperledger/solang-substrate-ci:62a8a6c substrate-contracts-node --dev --rpc-external -lwarn,runtime::contracts=trace) >> $GITHUB_OUTPUT
        id: substrate

      # Download Solang binary
      - uses: actions/download-artifact@v4.1.8
        with:
          name: solang-linux-x86-64
          path: bin
      - run: |
          chmod 755 ./bin/solang
          echo "$(pwd)/bin" >> $GITHUB_PATH

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
      - run: npm install
        working-directory: ./integration/polkadot

      # Build ink! contracts
      - name: Build ink! contracts
        run: npm run build-ink
        working-directory: ./integration/polkadot

      # Build Solang contracts
      - name: Build Solang contracts
        run: npm run build
        working-directory: ./integration/polkadot

      # Deploy and test contracts
      - name: Deploy and test contracts
        run: npm run test
        working-directory: ./integration/polkadot

      # Upload test coverage files
      - name: Upload test coverage files
        uses: actions/upload-artifact@v4.4.0
        with:
          name: polkadot-tests
          path: ./target/*.profraw

      # Cleanup substrate container
      - name: Cleanup
        if: always()
        run: docker kill ${{ steps.substrate.outputs.id }}
